### ISSUE TITLE
docker stack deploy komutu çalışırken aldığım hata (Ubuntu 20.04)

### ISSUE THREAD

**Issue by erdodo** [mikroGovernment/angaryos-stack#77]
`failed to create service angaryos_frontendBuilder: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceeded`
docker paketleri kurulurken bi anda böyle bir hata ile karşılaştım 

`
Creating network angaryos_elk-nw 
Creating network angaryos_mq-nw
Creating network angaryos_mobil-nw
Creating network angaryos_default
Creating network angaryos_db-nw
Creating network angaryos_backend-nw
Creating service angaryos_memcached
Creating service angaryos_logstash
Creating service angaryos_ftpServer
Creating service angaryos_kibana
Creating service angaryos_laravel
Creating service angaryos_frontendBuilder
failed to create service angaryos_frontendBuilder: Error response from daemon: network angaryos_frontend-nw not found
`

**Comment by omersavas26** [comment]
Aynı makine üzerindeki eski bir angaryos kurulumu rm komutu ile kaldırılmış ama halihazırda docker kaynakları tamamen kaldırılmış değil. Docker daemon servisini yada kolayca makineyi yeniden başlatarak tekrar denersen çalışacaktır.

**Comment by omersavas26** [comment]
Bu stack bu hafta içinde kullanımdan kaldırılmış olacak. https://github.com/mikroGovernment/angaryos Yeni angaryos u kullanmaya başladık biz artık :)
